### PR TITLE
fix: add store assets

### PR DESCRIPTION
**Pull request by LooterToGo**

### CODE REVIEW

**Review by ChipWolf — CHANGES_REQUESTED** [review]
Please fix inconsistent and non-descriptive file naming, stick to one of `_` or `-` for logical seperation, remove spaces and unnecessary numbers, and only use lower-case.

**Comment by LooterToGo** [comment]
I'll fix the descriptive file naming after I edit index.html

**Review by fatsnorlax — DISMISSED** [review]
Meant to comment.  LGTM without the approve. Every file is in there.

**Comment by fatsnorlax** [comment]
@ChipWolf Could you take a look at this?

**Review by ChipWolf — APPROVED** [review]
LGTM

**Pull request merged**
